# Data Encoding

1. Nominal or ONE-Hot encoding
2. Label or ordinal encoding
3. Target Guided Ordinal Encoding

# 1. Nominal or ONE-Hot encoding
 

 ### sparse matrix created due to  OHE -> overfitiing (Disadvantage)

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df = pd.DataFrame(
    {
        'color' : ["red",'green','red',' blue','yellow','orange']
    }
)

In [5]:
df.head()

    color
0     red
1   green
2    blue
3  yellow
4  orange

In [6]:
enc = OneHotEncoder()

In [13]:
#perform fit and transform

encoded = enc.fit_transform(df[['color']]).toarray()

In [15]:
encoded

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.]])

In [17]:
import pandas as pd 
encoder_df  = pd.DataFrame(encoded, columns = enc.get_feature_names_out())

In [18]:
encoder_df

   color_ blue  color_green  color_orange  color_red  color_yellow
0          0.0          0.0           0.0        1.0           0.0
1          0.0          1.0           0.0        0.0           0.0
2          0.0          0.0           0.0        1.0           0.0
3          1.0          0.0           0.0        0.0           0.0
4          0.0          0.0           0.0        0.0           1.0
5          0.0          0.0           1.0        0.0           0.0

In [23]:
enc.transform([['red']]).toarray()

d:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 1., 0.]])

In [24]:
pd.concat([df,encoder_df],axis= 1)

    color  color_ blue  color_green  color_orange  color_red  color_yellow
0     red          0.0          0.0           0.0        1.0           0.0
1   green          0.0          1.0           0.0        0.0           0.0
2     red          0.0          0.0           0.0        1.0           0.0
3    blue          1.0          0.0           0.0        0.0           0.0
4  yellow          0.0          0.0           0.0        0.0           1.0
5  orange          0.0          0.0           1.0        0.0           0.0

In [27]:
import seaborn as sns 

df = sns.load_dataset('tips')

In [40]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [54]:
encoded_1 = enc.fit_transform(df[["day",'sex']]).toarray()

In [55]:
encoded_df =pd.DataFrame(encoded_1, columns = enc.get_feature_names_out())

In [56]:
encoded_df

     day_Fri  day_Sat  day_Sun  day_Thur  sex_Female  sex_Male
0        0.0      0.0      1.0       0.0         1.0       0.0
1        0.0      0.0      1.0       0.0         0.0       1.0
2        0.0      0.0      1.0       0.0         0.0       1.0
3        0.0      0.0      1.0       0.0         0.0       1.0
4        0.0      0.0      1.0       0.0         1.0       0.0
..       ...      ...      ...       ...         ...       ...
239      0.0      1.0      0.0       0.0         0.0       1.0
240      0.0      1.0      0.0       0.0         1.0       0.0
241      0.0      1.0      0.0       0.0         0.0       1.0
242      0.0      1.0      0.0       0.0         0.0       1.0
243      0.0      0.0      0.0       1.0         1.0       0.0

[244 rows x 6 columns]

In [57]:
pd.concat([df,encoded_df],axis=1)

,total_bill,tip,sex,smoker,day,time,size,day_Fri,day_Sat,day_Sun,day_Thur,sex_Female,sex_Male
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0,0.0,1.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0,0.0,1.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0,0.0,1.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,0.0,1.0,0.0,0.0,1.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0.0,1.0,0.0,0.0,0.0,1.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0.0,1.0,0.0,0.0,1.0,0.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0,0.0,0.0,0.0,1.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0.0,1.0,0.0,0.0,0.0,1.0
243,18.78,3.00,Female,No,Thur,Dinner,2,0.0,0.0,0.0,1.0,1.0,0.0